### ISSUE TITLE
Infografía de Librerías.

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-de-las-librerias-Yabin-2021#2]
Anexo la infografía de las librerías SPRINT 2.
Es en línea, darl click y verla en línea. (Por los servicios de Canva).

https://www.canva.com/design/DAEbv8BDRc0/KiyVpJZbblJUUM3el4hHJw/view?utm_content=DAEbv8BDRc0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by salathiel1999** [comment]
Evaluación: 18.0%
Evaluación: Irvin Barrera

**Comment by josealfredo79** [comment]
Bien hecho y revisado
